task: kettle
mode: train
train:
  lr: 1e-4
  epoch: 8
  horizon: 100
  ent_coef: 1e-3
  proc_num: 20
  in_proc_env_num: 1
  max_timestep: 2000000
  dataset_path: "assets/grasp/TOGSample"
model:
  pi:
    - 128
    - 128
  vf:
    - 128
    - 64
  activation: ReLU

